### PR TITLE
Update to 1.10

### PR DESCRIPTION
**Pull request by phase**
This is the 1.10 update!
## Changes so far
- Instead of using MCP's mappings, we're using [Mountain](https://github.com/FountainMC/Mountain/).
- All the decompiler errors have been fixed
## Changes that need to happen
- Fix Fountain code to use the new mappings.
- Add the NMS patches that dealt with Fountain code.
- Update scripts to use Mountain.
  - Create scripts to merge new mappings from Mountain.

### CODE REVIEW

**Comment by Techcable** [comment]
I like dropping the dependency on MCP.

**Comment by wgaylord** [comment]
I don't like the idea of spigot mappings but. As there license is unclear. (Does not have one in there repo...)

**Comment by phase** [comment]
@chibill $20 says it's better than MCP's, as their's is "you can use this, but you can't look, touch, smell, or use this."

**Comment by wgaylord** [comment]
Yeah but with out packages it make it over 100% harder to deal with.

**Comment by phase** [comment]
@chibill That's the whole point of adding our own mappings! They move it into new packages and update methods and such.

**Comment by wgaylord** [comment]
And make it hard on devs that want to use methods that are built into MC.

**Comment by chibill** [comment]
Also not sure how I got pulled into this project... Sort of wanted to just deal with ForgedBukkit.

**Comment by Techcable** [comment]
Actually you know as @0x277F pointed out the spigot mappings aren't really licensed for us.
And its not really a problem waiting for MCP to update since most people won't use a new version until forge updates.

**Comment by phase** [comment]
Supporting the latest version is a lot better than waiting for MCP to update. How many servers are running Spigot 1.10? A lot more than are running Forge 1.9.4. I'm sure we can get permission to use Spigot's mappings.

> And make it hard on devs that want to use methods that are built into MC.

That's the whole point of these mappings. They give obfuscated methods new names.

**Comment by phase** [comment]
We're sticking to MCP.

**Pull request closed without merging**
