### PR TITLE
Basic entity implementation with new events implemented

### PR DESCRIPTION
**Pull request by PizzaCrust**
- EntitySpawnedEvent (implemented)
- EntityRemovedEvent (implemented)
- Entity (tree fully implemented)
  - Living
    - Player

There's a duplicate commit. I don't know how it got there.

### CODE REVIEW

**Comment by Techcable** [comment]
I'll squash and reformat this :)

**Comment by PizzaCrust** [comment]
Thanks.

**Comment by phase** [comment]
I had a different idea for Entities. Instead of creating new Wet classes, we can have the Entity classes implement our interfaces and implement the methods inside the classes.

**Comment by PizzaCrust** [comment]
Ok.

**Comment by Techcable** [comment]
@phase That'd make a much much bigger diff

**Comment by phase** [comment]
It would just add `implements org.fountainmc.api.entity.Blah` and add the methods at the bottom. I don't think it'd be too horrible.

**Comment by PizzaCrust** [comment]
Mixins :package:

**Comment by phase** [comment]
@Techcable A rebase might be better to keep the hook listener commit. Just reword them and remove the "merged github" commit.

**Comment by phase** [comment]
Merged in https://github.com/FountainMC/Fountain/commit/74f932d9bdd67cf83b341f932ce8699874813d0a and https://github.com/FountainMC/Fountain/commit/717c593066059e82f008bc36244d6448d2d9dbdb.

**Comment by Techcable** [comment]
@phase messed this up so I'll be doing this 😉 along with the other entity implementations.

**Comment by Techcable** [comment]
Nevermind, I guess he did merge it

**Comment by phase** [comment]
Yeah, _because I'm a git wizard_.

**Pull request closed without merging**
